### ISSUE TITLE
Trackpoint not scrolling with middle-click

### ISSUE THREAD

**Issue by agscala** [seven-of-eleven/Lenovo-ThinkPad-X1C7-OC-Hackintosh#11]
Do you have any issues with your trackpoint not scrolling properly when you hold the middle mouse button?

I tried upgrading `VoodooPS2Controller.kext` to the latest version, but it still isn't working.

I'm pretty new to the hackintosh scene, so if you'd have some suggestions on where I can poke around to figure out why isn't not working, I'd appreciate it!

**Comment by madeline-xoxo** [comment]
this behaviour doesnt occur for me on linux or windows?
