### ISSUE TITLE
SSDT-Batt

### ISSUE THREAD

**Issue by Lafite-Yu** [seven-of-eleven/Lenovo-ThinkPad-X1C7-OC-Hackintosh#3]
I just installed Mac OS 12.3 with your EFI, but there is no battery in the preference setting. Is the SSDT-Batt file on github the correct working version? Thanks.

**Comment by seven-of-eleven** [comment]
Hi. Not sure if you have this figured out yet, but yes the SSDT-Batt file is working for me. Have you tried to clear you NVRAM?
