### ISSUE TITLE
Stuck On Pre-Installation

### ISSUE THREAD

**Issue by markchen8717** [seven-of-eleven/Lenovo-ThinkPad-X1C7-OC-Hackintosh#5]
### Specs
Type: 20QD
CPU: Intel(R) Core(TM) i5-8265U
GPU: Intel UHD 620
SSD: Western Digital SN720 SSD 256GB
Screen: 14" 1080p SDR
Memory: 16GB / 2133MHz LPDDR3
Wifi & BT: Intel Wireless-AC 9560

### Steps to reproduce

1. Followed the steps to [Making the installer in Windows](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html)
2. Copy and pasted the EFI folder from this repo into USB root
![image](https://user-images.githubusercontent.com/29904105/170827944-d6f8f20d-9069-4277-b2c0-230fafa717cc.png)
![image](https://user-images.githubusercontent.com/29904105/170827950-f425d906-6ea0-401e-9196-418a5076db62.png)
3. Apply pre installation BIOS settings shown in the repo
4. Boot into USB and select EFI

### Expected Behavior
The pre-installation phase of the Apple logo and loading bar should finish and be presented with the installation screen.

### Actual Behavior
The screen is stuck at the pre-installation phase of the Apple logo and loading bar (with less than 10% loaded)

### Debug (the tail of the error file)
`222:074 00:043 AAPL: #[EB.LD.OFS|OPEN!] Err(0xE) <"usr\\standalone\\OS.dmg.root_hash">`
`222:111 00:037 AAPL: #[EB.RH.LRH|P!] Err(0xE) <- EB.LD.LF`
`222:149 00:037 AAPL: #[EB.BST.FBS|!] Err(0xE) <- EB.RH.LRH`

The full debug error file can be seen [here](https://gist.github.com/markchen8717/8819eb4d668c344bc9423cb9ab3f1d79)

**Comment by seven-of-eleven** [comment]
Hi @markchen8717 Sorry for the delayed response. I've never created boot disk with Windows so I'm not sure what problems that could be causing. Do you know if that method creates a complete boot disk or if you need an internet connection during install?  Assuming you're installing Monterey how long did you wait for it to boot?

**Comment by markchen8717** [comment]
Hey @seven-of-eleven, thanks for getting back to me. You are right that this method doesn't create a complete boot disk and requires an internet connection during install. However, I am not sure if it starts the downloading during the pre-installation phase (where the screen only shows the Apple logo and loading bar) or afterwards inside the welcome screen. I did wait for it to load in the pre-installation phase for ~20 mins. Will try this out again with a boot disk created on MAC.

**Comment by seven-of-eleven** [comment]
Try also adding "-v" to your boot-args key in the config.plist file as outlined [here](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake.html#nvram).  It will provide verbose booting and may give more insight to the issue.

**Comment by markchen8717** [comment]
Hey @seven-of-eleven, so I went through the USB creation method on a MAC virtual machine, and also added `-v` to my boot args. This time I was not even able to make it into the Apple logo loading screen. However, I was able to capture a screenshot of the errors below.
![IMG_7400](https://user-images.githubusercontent.com/29904105/173934331-db334eb3-1a24-4a96-aea5-ef5cba87263c.JPG)

**Comment by seven-of-eleven** [comment]
Looks like it is getting hung up with the WiFi/Bluetooth. Not sure why. If you are installing Monterey the proper Kext files should be in the EFI folder. I am running 12.4 on my computer as well.  Try disabling AirportItlwm.kext, BluetoolFixup.kext, and IntelBluetoothFirmware.kext in you config.plist file (set the "Enabled" key to `False` for **each**). Then try the install again. If it does boot/install then at least you've narrowed down where the issue is. I hope to update my EFI to the latest version of OpenCore over the next week as well, if you'd prefer to wait for the updated version. Best.

**Comment by markchen8717** [comment]
I tried booting back into v12.4 again and got stuck in a different screen, this is before I disabled the wifi / bluetooth kexts.
![IMG_7406](https://user-images.githubusercontent.com/29904105/174415076-a4abd594-3f1b-4985-9d78-7f32abf99472.JPG)

**Comment by NotARobot6969** [comment]
@markchen8717 Can you be sure it is stuck? It might just be loading.

**Comment by markchen8717** [comment]
Hey @NotARobot6969, I gave it another stab, it got stuck over 45 minutes on the screen below. The light on my USB was not blinking at all within this duration. I also tried disabling the network kext suggested by @seven-of-eleven, but no luck :/
![IMG_7414](https://user-images.githubusercontent.com/29904105/175454710-6fee6b84-048e-4342-ab7d-d6eb8aacb2f7.JPG)

**Comment by seven-of-eleven** [comment]
@markchen8717 Not sure if you've tried the updated EFI with OC-0.8.1? Let me know if you're having issue with that version as well. Also did you set your [Serial numbers](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake.html#platforminfo). Also try and reset your NVRAM after changing the config.plist file.

**Comment by markchen8717** [comment]
Hey @seven-of-eleven, I tried out the updated EFI with OC 0.8.1 and got into a restart boot loop before seeing the apple logo. I want to confirm with you whether the steps I've taken to setup my EFI folder is correct. So I basically copy over the EFI folder from this repo onto the OC 0.8.1 RELEASE x64 EFI by replacing any files that already exists. Then I use genSMBIOS to set my serial numbers. Please let me know if I am missing some steps to create the EFI folder correct, thanks!
P.S I've tried resetting my NVRAM after changing the config.plist file but still no luck.

**Comment by markchen8717** [comment]
Thanks for the swift and detailed reply @seven-of-eleven! I tried copying the EFI folder directly from this repo into the EFI partition of the drive and unfortunately it still crashes during boot. By the way, I used the `Install_macOS_12.3.1-21E258.dmg` to create my USB. Please correct me if this is the wrong version.

**Comment by NotARobot6969** [comment]
hi @markchen8717! your issue may be stemming from creating a USB from an install dmg and not download from macrecovery? maybe try using the basesystem and chunklist from macrecovery.

**Comment by markchen8717** [comment]
Hey @NotARobot6969, thanks for pitching in! Just double checking I understood you correctly, to use the basesystem and chunklist from macrecovery, is this the online method to create a USB using the Windows method at https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos ?

**Comment by NotARobot6969** [comment]
@markchen8717 yep! it might make a difference as you're downloading the very latest version

**Comment by markchen8717** [comment]
Thanks @NotARobot6969 !! Will give this a try right now!

**Comment by markchen8717** [comment]
Hey @NotARobot6969 and @seven-of-eleven, so I attempted the Mac recovery method on the latest release but the boot restart still occurs. However, I went back to release 1.1 and tried that out and my laptop has been stuck on this screen for over 30 mins. Any ideas about these fail messages? ![image](https://user-images.githubusercontent.com/29904105/177433812-b7073d72-b3d3-4b10-be8c-03bd35ee28d1.jpg)

**Comment by markchen8717** [comment]
Good news @seven-of-eleven and @NotARobot6969! After removing just the `device_id` entry from the config.plist, I was able to enter the installation GUI! 

Since I want to dual boot both windows and Mac OS, I shrunk my Windows volume and created a new volume with the unallocated space. Then proceed to start the recovery installation.  [Found this video to dual boot Big Sur](https://www.youtube.com/watch?v=XAHSkwbIb7k&t=1329s) Unfortunately, the installer has been stuck for over 2 hours with no restarts.

Going to try to create the USB from a MAC and see. Nonetheless, thank you guys once again!!

**Comment by markchen8717** [comment]
Good news @seven-of-eleven and @NotARobot6969! After removing just the `device_id` entry from the config.plist, I was able to enter the installation GUI! 

Since I want to dual boot both windows and Mac OS, I shrunk my Windows volume and created a new volume with the unallocated space. Then proceed to start the recovery installation.  [Found this video to dual boot Big Sur](https://www.youtube.com/watch?v=XAHSkwbIb7k&t=1329s) Unfortunately, the installer has been stuck for over 2 hours with no restarts.
![IMG_7440](https://user-images.githubusercontent.com/29904105/178119472-5a774b1f-51ca-4c2e-97a0-4df6f4783047.JPG)

Going to try to create the USB from a MAC and see. Nonetheless, thank you guys once again!!

**Comment by markchen8717** [comment]
I've successfully installed Monterey with the MAC created USB and booted into it! Thanks @NotARobot6969  @seven-of-eleven for all the help walking be through this !!

**Comment by mlabajos456** [comment]
How did you solve it?
