### ISSUE TITLE
HDMI not working with `-igfxmlr` boot flag

### ISSUE THREAD

**Issue by seven-of-eleven** [seven-of-eleven/Lenovo-ThinkPad-X1C7-OC-Hackintosh#7]
Hey @seven-of-eleven and @penholderu, great news, so I took the latest default config.plist from the repo and removed `-wegnoegpu` and added `-igfxmlr` and was able to boot with graphics acceleration.

However, connecting to an external monitor doesn't work for both direct HDMI connection or USB-C dongle connection. 

@penholderu any luck with external monitor connections?

_Originally posted by @markchen8717 in https://github.com/seven-of-eleven/Lenovo-ThinkPad-X1C7-OC-Hackintosh/issues/6#issuecomment-1184837066_

**Comment by markchen8717** [comment]
Hey @seven-of-eleven, I noticed that your bios is 1.41 (N2HET58W), I ran `wmic bios get smbiosbiosversion` in cmd and it shows 1.41 (N2HET58W) for me as well. However, looking at your bios screen shots, it looks different from mine. The UI on mine looks newer and I can use my mouse in it. Here is a screenshot from my system info 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/29904105/179246177-deba5370-0fad-4de0-9271-5eda03a16e05.png">

**Comment by markchen8717** [comment]
Hey @seven-of-eleven and @NotARobot6969, I got some great news.
I came across this [guide.](https://www.reddit.com/r/hackintosh/comments/hu46xm/fix_hdmi_port_and_possibly_others_not_working_on/)
After re generating the SMBIOS to `MacBookPro15,4`, and my device properties to the below:
![image](https://user-images.githubusercontent.com/29904105/179321351-21882061-e846-48b5-91dd-1659fb8deca2.png)
External monitor connection works!
Just want to double check with you guys whether I edit the USBMap.kext file correct. So inside the info.plist I searched for any keys/values that has the old `MacBookPro15.1` and replaced it with `MacBookPro15,4`. Is this sufficient? Thanks!
![image](https://user-images.githubusercontent.com/29904105/179322230-43e1954b-b84b-4423-9940-3b04598ae497.png)

**Comment by seven-of-eleven** [comment]
@markchen8717 great to hear HDMI is working. With regards to the USBMap.kext, it seems you've changed it properly. Worst case if something is not working properly you can redo the USB mapping but you should be fine.  Congrats on getting things working.
